---
- name: Install EPEL repo
  package:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - python2-pip
    - python2-setuptools
    - python-tools
    - tmux
    - vim
    - bridge-utils

- name: Install stack user
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    createhome: yes

- name: sudo for stack user
  copy:
    dest: /etc/sudoers.d/stack
    content: "stack ALL=(ALL) NOPASSWD: ALL\n"

- name: Add docker group and add the stack user to the docker group
  shell: sudo groupadd docker && sudo gpasswd -a stack docker

- name: CentOS workaround
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools


- name: Clone devstack repo
  become_user: stack
  become: yes
  git:
    repo: https://git.openstack.org/openstack-dev/devstack
    dest: /opt/stack/devstack

- name: Get local.conf
  become_user: stack
  become: yes
  vars:
    host_ip: "{{ ansible_default_ipv4.address }}"
  template:
    src: "{{ local_conf | default('kuryr.conf') }}"
    dest: /opt/stack/devstack/local.conf

- name: Run devstack
  become: yes
  become_user: stack
  shell: cd /opt/stack/devstack && ./stack.sh
