---
- name: Allow VXLAN
  become: yes
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: 4789
    ctstate: NEW
    jump: ACCEPT
    comment: Accept VXLAN connections.

- name: Run update
  become: yes
  shell: apt update -y 

- name: Run upgrade
  become: yes
  shell: sudo apt install unattended-upgrades && apt -y upgrade
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Run update
  become: yes
  shell: apt -y dist-upgrade

- name: Run reboot 
  become: yes
  reboot:
    reboot_timeout: 3600

- name: Install packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - tmux
    - vim
    - bridge-utils

- name: Install stack user
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
    createhome: yes

- name: sudo for stack user
  copy:
    dest: /etc/sudoers.d/stack
    content: "stack ALL=(ALL) NOPASSWD: ALL\n"

- name: Ensure group "docker" exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present  

- name: Ensure user "docker" exists
  become: yes
  ansible.builtin.user:
    name: docker
    state: present  

#- name: Clone devstack repo
#  become_user: stack
#  become: yes
#  git:
#    repo: https://opendev.org/openstack/devstack.git
#    dest: /opt/stack/devstack

- name: Clone devstack repo
  become_user: stack
  become: yes
  shell: 
    cmd: git clone -b {{ devstack_branch }} https://opendev.org/openstack/devstack.git
    chdir: /opt/stack

- name: Get local.conf
  become_user: stack
  become: yes
  vars:
    host_ip: "{{ ansible_default_ipv4.address }}"
  template:
    src: "{{ local_conf | default('local.conf') }}"
    dest: /opt/stack/devstack/local.conf

- name: Run devstack
  become: yes
  become_user: stack
  shell: cd /opt/stack/devstack && ./stack.sh
